#!/bin/bash

datestr=$1

if [ -z $1 ]
then
	datestr=$(date +%Y-%m-%d)
fi

echo "isolate $datestr"

rake isolate[$datestr]
mv source/_posts/legacy source/_stash/

rake generate
rake preview

rake integrate
mv source/_stash/legacy source/_posts/

